### ISSUE TITLE
Slave address was not acknowledged

### ISSUE THREAD

**Issue by msiggi** [Rinsen/OneWire#1]
Hi,

thank you for your code, but I had no success with it. I used an schematic like http://www.raspi.cz/wp-content/uploads/2012/11/ds2482-1_bb.jpg and I get this exception in the catch-block in your sample code in LogTemperatures(ThreadPoolTimer timer):

{System.IO.FileNotFoundException: The system cannot find the file specified.

Slave address was not acknowledged.
   at Windows.Devices.I2c.I2cDevice.Write(Byte[] buffer)
   at Rinsen.IoT.OneWire.DS2482_100.OneWireReset()
   at Rinsen.IoT.OneWire.OneWireDeviceHandler.GetConnectedOneWireDevices()
   at Rinsen.IoT.OneWire.OneWireDeviceHandler.get_OneWireDevices()
   at Rinsen.IoT.OneWire.OneWireDeviceHandler.GetDevices[T]()
   at OneWire.StartupTask.LogTemperatures()}

Maybe you have an idea?

**Comment by Rinsen** [comment]
Hi!
This is probably related to failing I2C communication with the DS2482 chip, I have found a bug in my implementation where I used a hard coded address instead of the configured via OneWireDeviceHandler ctor. I will fix this and deply an updated version to nuget later today.

And it is realy a terrible error message, I will try to do something with this...

**Comment by msiggi** [comment]
Hi,

we have a summer-day here in in germany - 26,1 Grd Celsius sends my DS18S20 from my hobby-room. Thank you, now your library works!

I create a new VisualStudio-Project "Background Application (IoT)", add your nuget-package and I get the correct temperature (I have to use `new OneWireDeviceHandler(false, false)` - I don´t know why, but it works) in the VisualStudio-debugger - very nice!

But I want to create a headed App, so I create a "Blank App (Windows Universal)", add the IoT-Libraries described here (http://ms-iot.github.io/content/en-US/win10/samples/HelloWorld.htm), add your package - I have no success. The program stops at `DeviceInformation.FindAllAsync(aqs)` 
 (I integrated your code instead of the nuget-package) and comes never back!

What is the difference?

**Comment by Rinsen** [comment]
Hi! I'm glad to hear that the first problem is solved!

I will try to recreate the headed app problem, but I haven't done any headed apps with this yet so I don't have any idea right now.

**Comment by Rinsen** [comment]
I get the same problem as you.

And I have also updated the projects to the latest Windows 10 type now and updated my Raspberry Pi to the latest build but no changes. So I don't really know what the problem is right now and don't really know how to fix it eater. When i get more time i will try to do some more investigation to this issue but I will create a separate issue for this.

**Comment by Rinsen** [comment]
You will now get a better error when no DS2482-100 is found.

https://github.com/Rinsen/OneWire/commit/f5c24463fffbec0f24b7c1f7836366b696a2fedc

**Comment by Rinsen** [comment]
@msiggi 

I have actually solved the issue with headed apps now after a looooong time :)
